---
- hosts: localhost
  become: yes
  become_user: root
  pre_tasks:
    - name: be sure apt cache is updated
      apt: update_cache=yes

  tasks:
    # pre-reqs for apt_repository
    - name: install pre-requisites
      apt: pkg={{ item }} state=present
      with_items:
        - python-pycurl
        - python-apt
        - software-properties-common


    - name: Accept Java 8 License
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Added repositories
      apt_repository: repo="{{ item }}" update_cache=yes
      with_items:
        - "ppa:webupd8team/sublime-text-3"
        - "ppa:webupd8team/java"


    - name: install software
      apt: pkg={{ item }} state=present
      with_items:
        - git-core
        - build-essential
        - gcc
        - g++
        - valgrind
        - gdb
        - cgdb
        - clang-3.4
        - emacs23
        - vim
        - gedit
        - eclipse
        - kate
        - geany
        - codeblocks
        - sublime-text-installer
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default


    - name: Create group apc-users
      group: name="apc-users" state=present

    - name: Create apc-user in apc-users group
      user: name="apc-user" group="apc-users" password="$6$YOwXZ5K5$Bw02lwhePddxZo/N1TswAOD9PHFcVTDfvJGLLokwrhsZyI.NgRqRhKUFvIHOydM/jL.PhTeVUkVTfCpYm4jsc1"


    - name: add domjudge-server hostname
      lineinfile: dest=/etc/hosts line="145.100.98.5 judge.svia.nl" state=present
      tags: test1

    - name: prevent the iptables-peristent install dialog
      debconf: name=iptables-persistent question={{ item }} vtype=boolean value=true
      with_items:
      - iptables-persistent/autosave_v4
      - iptables-persistent/autosave_v6
      tags: iptest

    - name: Install iptables-persistent
      apt: pkg=iptables-persistent state=present
      tags: iptest

    - name: clear IPtable and install rules
      command: iptables {{ item }}
      with_items:
      - -F
      - -P INPUT ACCEPT
      - -P FORWARD DROP
      - -P OUTPUT ACCEPT
      - -A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
      - -A INPUT -m state --state INVALID -j DROP
      - -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
      - -A INPUT -s 145.100.98.5/32 -j ACCEPT
      - -A INPUT -i lo -j ACCEPT
      - -A INPUT -p udp --dport 67:68 --sport 67:68 -j ACCEPT
      - -A INPUT -j REJECT --reject-with icmp-port-unreachable
      - -A OUTPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
      - -A OUTPUT -d 145.100.98.5/32 -j ACCEPT
      - -A OUTPUT -p udp --dport 67:68 --sport 67:68 -j ACCEPT
      - -A OUTPUT -j REJECT
      tags: iptest

    - name: Save iptable rules to file.
      shell: iptables-save > /etc/iptables/rules.v4
